#!/usr/bin/env sh

main_loop() {
	while ping -c 1 archlinux.org; do
		~/.config/scripts/weather.sh --getdata
		sleep 300
	done
  ~/.config/scripts/weather.sh --getdata
	int_loop
}

int_loop() {
	while ! ping -c 1 archlinux.org; do
		sleep 10
	done
	main_loop
}

main_loop
