#!/bin/sh

BAT=/sys/class/power_supply/BAT1

per=$(cat "$BAT"/capacity)
status=$(cat "$BAT"/status)

colcharge="#50fa7b"
colgood="#8be9fd"
colwarn="#ffb86c"
colcrit="#ff5555"

if [ "$status" = "Discharging" ]; then
  if [ "$per" -gt "90" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "80" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "70" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "60" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "50" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "40" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "30" ]; then
	  icon=""
		col="$colgood"
  elif [ "$per" -gt "20" ]; then
	  icon=""
		col="$colwarn"
  elif [ "$per" -gt "10" ]; then
	  icon=""
		col="$colcrit"
	else
	  icon=""
		col="$colcrit"
		notify-send -u critical "Battery Low" "Connect Charger"
	fi
elif [ "$status" = "Charging" ]; then
	icon=""
	col="$colcharge"
else
	icon=""
	col="$colcrit"
fi

if [ "$1" = "--COL" ]; then
	echo "$col"
elif [ "$1" = "--STATUS" ]; then
	echo "$status"
elif [ "$1" = "--ICON" ]; then
	echo "$icon"
elif [ "$1" = "--CAP" ]; then
	echo "$per"
fi
