#!/usr/bin/env sh

power_supply=/sys/class/power_supply/ACAD/online
bat_per=$(cat /sys/class/power_supply/BAT1/capacity)

colcharge="#50fa7b"
colgood="#8be9fd"
colwarn="#ffb86c"
colcrit="#ff5555"

if grep -q "0" $power_supply; then
	if [ "$bat_per" -gt "90" ]; then
		icon="󰂂"
		col="$colgood"
	elif [ "$bat_per" -gt "80" ]; then
		icon="󰂁"
		col="$colgood"
	elif [ "$bat_per" -gt "70" ]; then
		icon="󰂀"
		col="$colgood"
	elif [ "$bat_per" -gt "60" ]; then
		icon="󰁿"
		col="$colgood"
	elif [ "$bat_per" -gt "50" ]; then
		icon="󰁾"
		col="$colgood"
	elif [ "$bat_per" -gt "40" ]; then
		icon="󰁽"
		col="$colgood"
	elif [ "$bat_per" -gt "30" ]; then
		icon="󰁼"
		col="$colgood"
	elif [ "$bat_per" -gt "20" ]; then
		icon="󰁻"
		col="$colwarn"
	elif [ "$bat_per" -gt "10" ]; then
		icon="󰁺"
		col="$colcrit"
		notify-send -u critical "Battery Low" "Connect Charger"
	else
		icon="󰂎"
		col="$colcrit"
		notify-send -u critical "Battery Low" "Connect Charger"
	fi
elif grep -q "1" $power_supply; then
	icon=""
	col="$colcharge"
else
	icon="󰂃"
	col="$colcrit"
fi

if [ "$1" = "--COL" ]; then
	echo "$col"
elif [ "$1" = "--ICON" ]; then
	echo "$icon"
fi
