#!/usr/bin/env sh

# Script that run in background to control screen brightness
bright_script="bash $HOME/.config/autostart/screen_brightness.sh"

# Process ID of script
bright_PID=$(pgrep -f "$bright_script")

# Toggle process | STOP/CONT
if [ "$(ps -o state= -p "$bright_PID")" = S ]; then
	kill -STOP "$bright_PID"
elif [ "$(ps -o state= -p "$bright_PID")" = T ]; then
	kill -CONT "$bright_PID"
fi
