#!/usr/bin/env sh

status=$(pamixer --get-mute | grep -oE "true")
percent=$(pamixer --get-volume)

if [ "$status" ]; then
	icon="󰝟"
	col="#ff5555"
else
	if [ "$percent" -ge 66 ]; then
		icon="󰕾"
	elif [ "$percent" -ge 33 ]; then
		icon="󰖀"
	else
		icon="󰕿"
	fi
	col="#bd93f9"
fi

if [ "$1" = "--COL" ]; then
	echo "$col"
elif [ "$1" = "--PERC" ]; then
	echo "$percent"
elif [ "$1" = "--ICON" ]; then
	echo "$icon"
fi
