#!/bin/sh

status=$(pamixer --get-mute | grep -oE "true")
percent=$(pamixer --get-volume)

if [ "$status" ] ; then
    icon="婢"
    col="#ff5555"
else
    icon=""
    col="#bd93f9"
fi

if [ "$1" = "--COL" ]; then
    echo $col	
elif [ "$1" = "--PERC" ]; then
	echo "$percent"
elif [ "$1" = "--ICON" ]; then
	echo $icon
fi
