#!/bin/sh

main_loop() {
  while ping -c 1 archlinux.org; do
    ~/.config/eww/scripts/weather --getdata
    sleep 300
  done
  int_loop
}

int_loop() {
  while ! ping -c 1 archlinux.org; do
    sleep 10
  done
  main_loop
}

main_loop
