#!/bin/bash
# Original from https://github.com/DashieTM/dotFiles/blob/main/eww/scripts/weather

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_hex=${cache_dir}/weather-hex
cache_weather_icon=${cache_dir}/weather-icon

## Weather data | openweatherdata file first line key second line id
KEY=$(awk 'NR == 1' ~/.config/eww/scripts/openweatherdata)
ID=$(awk 'NR == 2' ~/.config/eww/scripts/openweatherdata)
UNIT="imperial"	# Available options : 'metric' or 'imperial'

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p "${cache_dir}"
fi

## Get data
get_weather_data() {
	weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$KEY&id=$ID&units=$UNIT")
	echo "${weather}"

	if [ -n "$weather" ]; then
		weather_temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
		weather_icon_code=$(echo "$weather" | jq -r ".weather[].icon" | head -1)
		weather_description=$(echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g")

		#Big long if statement of doom
		if [ "$weather_icon_code" == "50d" ] || [ "$weather_icon_code" == "50n" ]; then
			weather_icon=" "
			weather_hex="#8be9fd"
		elif [ "$weather_icon_code" == "01d" ]; then
			weather_icon=" "
			weather_hex="#ffb86c"
		elif [ "$weather_icon_code" == "01n" ]; then
			weather_icon=" "
			weather_hex="#ff79c6"
		elif [ "$weather_icon_code" == "02d" ]; then
			weather_icon=" "
			weather_hex="#bd93f9"
		elif [ "$weather_icon_code" == "02n" ]; then
			weather_icon=" "
			weather_hex="#bd93f9"
		elif [ "$weather_icon_code" == "03d" ] || [ "$weather_icon_code" == "03n" ] || [ "$weather_icon_code" == "04d" ] || [ "$weather_icon_code" == "04n" ]; then
			weather_icon=" "
			weather_hex="#bd93f9"
		elif [ "$weather_icon_code" == "09d" ] || [ "$weather_icon_code" == "09n" ] || [ "$weather_icon_code" == "10d" ] || [ "$weather_icon_code" == "10n" ]; then
			weather_icon=" "
			weather_hex="#6272a4"
		elif [ "$weather_icon_code" == "11d" ] || [ "$weather_icon_code" == "11n" ]; then
			weather_icon=""
			weather_hex="#f1fa8c"
		elif [ "$weather_icon_code" == "13d" ] || [ "$weather_icon_code" == "10d" ]; then
			weather_icon=" "
			weather_hex="#f8f8f2"
		elif [ "$weather_icon_code" == "40d" ] || [ "$weather_icon_code" == "40n" ]; then
			weather_icon=" "
			weather_hex="#8be9fd"
		else 
			weather_icon=" "
			weather_hex="#bd93f9"
		fi
		echo "$weather_icon" >  "${cache_weather_icon}"
		echo "$weather_description" > "${cache_weather_stat}"
		echo "$weather_temp""°F" > "${cache_weather_degree}"
		echo "$weather_hex" > "${cache_weather_hex}"
	else
		echo "Unavailable" > "${cache_weather_stat}"
		echo " " > "${cache_weather_icon}"
		echo "" > "${cache_weather_degree}"
		echo "#bd93f9" > "${cache_weather_hex}"
	fi
}

## Execute
if [[ "$1" == "--getdata" ]]; then
	get_weather_data
elif [[ "$1" == "--icon" ]]; then
	cat "${cache_weather_icon}"
elif [[ "$1" == "--temp" ]]; then
	cat "${cache_weather_degree}"
elif [[ "$1" == "--hex" ]]; then
	cat "${cache_weather_hex}"
elif [[ "$1" == "--stat" ]]; then
	cat "${cache_weather_stat}"
fi

