#!/bin/sh

# Colors
good="#50fa7b"
bad="#ff5555"

# Network Interfaces
usb="usb0"
ethernet="eth0"
wifi="wlan0"
vpn="wg0"
rfblock=$(rfkill --output SOFT | awk '($1 == "blocked")')

network_check() {
  for interface in $(ls /sys/class/net/ | grep -v lo); do
    if [ $(cat /sys/class/net/$interface/carrier) = 1 ]; then
      OnLine=1
    fi
  done
  if ! [ $OnLine ]; then
    if [ "$rfblock" != "" ]; then
      icon=""
    elif [ $(nmcli general | grep -oE "disconnected") ]; then
      icon="睊"
    fi
    text=""
    col="$bad"
  else
    connection_type
  fi
}

connection_type() {
  #wifi
  if grep -q "1" /sys/class/net/$usb/carrier 2>/dev/null; then
    icon="禍"
    text="USB"
  elif grep -q "1" /sys/class/net/$ethernet/carrier 2>/dev/null; then
    icon=""
    text="Wired"
  elif grep -q "1" /sys/class/net/$wifi/carrier 2> /dev/null; then
    icon="直"
    text=$(nmcli connection | grep "$wifi" | awk '{print ($1)}')
  fi
  col="$good"
  if grep -q "1" /sys/class/net/$vpn/carrier 2>/dev/null; then
    icon="嬨"
  fi
}

network_check

if [ "$1" = "--ICON" ]; then
  echo "$icon"
elif [ "$1" = "--ESSID" ]; then
	echo "$text"
elif [ "$1" = "--COL" ]; then
	echo "$col"
fi

