#!/bin/bash

ic=(0  爵    碌 )

listworkspaces() {
  atleast=7
  ws=$(hyprctl -j workspaces | jq '.[].id' | sort)
  current=${1-$(hyprctl -j monitors | jq -r '.[0].activeWorkspace.id')}
  max=$(( ${ws[-1]} > atleast ? ${ws[-1]} : atleast))

  printf '(box :class "workspaces" :orientation "h" :spacing 3 :space-evenly "false" '
  for w in $(seq $max); do
    [[ $w == "$current" ]] && dot="${ic[$current]}" || dot="${ic[$w]}"
    if [[ $w == "$current" ]]; then
      class="focused"
    else
      if printf '%s\0' "${ws[@]}" | grep -Fxqz -- "$w"; then
        class="unfocused"
      else
        class="empty"
      fi
    fi

    printf '(button :class "%s" :onclick "hyprctl dispatch workspace %s" "%s")' "$class" "$w" "$dot"
  done
  echo -e ')'
}

listworkspaces "$@"
tail -f /tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/hyprland.log | grep -E --line-buffered "Changed to workspace" | while read -r; do 
listworkspaces "$@"
done
