#!/bin/sh

# i3block to show CPU temperature

temp=$(acpi -t | sed 's/.*, //;s/ degrees //;s/C//')
echo "$temp"糖 # full text
echo "$temp"糖 # short text

# color
if [ $(printf "%.0f" "$temp") -gt 85 ]; then
  echo "#ff5555"
fi
