#!/usr/bin/env bash

# Still working on a better way to do this, this is just a test at the moment

# Read /proc/stat file (for first datapoint)
read -r cpu user nice system idle iowait irq softirq steal guest </proc/stat

norm_color="#ffb86c"
warn_temp="60"
warn_color="#ff5555"

# compute active and total utilizations
cpu_active_prev=$((user + system + nice + softirq + steal))
cpu_total_prev=$((user + system + nice + softirq + steal + idle + iowait))

sleep .5

# Read /proc/stat file (for second datapoint)
read -r cpu user nice system idle iowait irq softirq steal guest </proc/stat

# compute active and total utilizations
cpu_active_cur=$((user + system + nice + softirq + steal))
cpu_total_cur=$((user + system + nice + softirq + steal + idle + iowait))

# compute CPU utilization (%)
cpu_util=$((100 * (cpu_active_cur - cpu_active_prev) / (cpu_total_cur - cpu_total_prev)))

echo "💻$cpu_util" # full text
echo "💻$cpu_util" # short text

# color
if [ "$cpu_util" -ge "$warn_temp" ]; then
  echo "$warn_color"
else
  echo "$norm_color"
fi

exit 0
