#!/bin/bash

# Still working on a better way to do this, this is just a test at the moment

# Read /proc/stat file (for first datapoint)
read -r cpu user nice system idle iowait irq softirq steal guest < /proc/stat

t_crit=80
t_warn=50
color_crit="#ff5555"
color_warn="#ff0000"

# compute active and total utilizations
cpu_active_prev=$((user+system+nice+softirq+steal))
cpu_total_prev=$((user+system+nice+softirq+steal+idle+iowait))

sleep .5

# Read /proc/stat file (for second datapoint)
read -r cpu user nice system idle iowait irq softirq steal guest< /proc/stat

# compute active and total utilizations
cpu_active_cur=$((user+system+nice+softirq+steal))
cpu_total_cur=$((user+system+nice+softirq+steal+idle+iowait))

# compute CPU utilization (%)
cpu_util=$((100*( cpu_active_cur-cpu_active_prev ) / (cpu_total_cur-cpu_total_prev) ))

echo "💻$cpu_util" # full text
echo "💻$cpu_util" # short text

# color
if [ "$cpu_util" -ge "$t_crit" ]; then
    echo "$color_crit"
elif [ "$cpu_util" -ge "$t_warn" ]; then
    echo "$color_warn"
fi

exit 0
