#!/usr/bin/env sh

# Mouse actions
case $BLOCK_BUTTON in
1) amixer -qM set Master 1+ toggle ;;
4) amixer -qM set Master 5%+ unmute ;;
5) amixer -qM set Master 5%- unmute ;;
esac

vol=$(amixer -M get Master | grep '%' | cut -d '[' -f 2 | cut -d '%' -f 1 | awk 'NR==1')
mute=$(amixer -M get Master | grep '%' | grep -oE '[^ ]+$' | grep off)

if [ "$mute" ]; then
  echo "🔇$vol"
  echo "🔇$vol"
  echo "#ff5555"
else
  if [ "$vol" -ge 80 ]; then
    echo "🔊$vol"
    echo "🔊$vol"
  elif [ "$vol" -ge 30 ]; then
    echo "🔉$vol"
    echo "🔉$vol"
  else
    echo "🔈$vol"
    echo "🔈$vol"
  fi
  echo "#bd93f9"
fi
