#!/usr/bin/env sh

vpn_type=wireguard
connection=$(nmcli connection show --active | grep "$vpn_type")

if [ "$connection" ]; then
  echo ""
  echo ""
  echo "#50fa7b"
else
  echo ""
  echo ""
  echo "#ff5555"
fi
