#!/bin/sh

# i3block for the displaying the wifi connectivity level

# Mouse actions
case $BLOCK_BUTTON in
  1) nm-connection-editor ;;
esac

# Colors
COLOR_GE80=${COLOR_GE80:-#50fa7b}
COLOR_GE60=${COLOR_GE60:-#50fa7b}
COLOR_GE40=${COLOR_GE40:-#ff5555}
COLOR_LOWR=${COLOR_LOWR:-#ff5555}
COLOR_DOWN=${COLOR_DOWN:-#ff5555}
COLOR_RKIL=${COLOR_RKIL:-#ff5555}

if [ "$1" = "" ] ; then
  wifi="wlan0"
else
  wifi="$1"
fi

if [ "$(cat /sys/class/net/"$wifi"/operstate)" = 'down' ]; then
  # If RFKILL is running else wifi disconnected
  if [ "$(rfkill list | awk -F ':' '/yes/ {print $2}')" ]; then
      echo ""
      echo ""
  else
      echo "睊"
      echo "睊"
  fi
  echo "$COLOR_RKIL"
  exit
fi

QUALITY=$(grep "$wifi" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

echo 直 "$QUALITY" # full text
echo 直 "$QUALITY" # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    echo $COLOR_GE40
else
    echo $COLOR_LOWR
fi
