#!/bin/sh

# Mouse actions
case $BLOCK_BUTTON in
  1) nm-connection-editor ;;
esac

# i3block for the displaying the wifi connectivity level
# If the wifi interface exists but no connection is active, "" shall be displayed in red.
#------------------------------------------------------------------------
if [ "$1" = "" ] ; then
  wifi="wlan0"
else
  wifi="$1"
fi

if [ "$(cat /sys/class/net/"$wifi"/operstate)" = 'down' ]; then
  # If RFKILL is running else wifi disconnected
  if [ "$(rfkill list | awk -F ':' '/yes/ {print $2}')" ]; then
      echo ""
      echo ""
  else
      echo "睊"
      echo "睊"
  fi
  echo "#ff5555"
  exit
fi

QUALITY=$(grep "$wifi" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

echo 直 "$QUALITY" # full text
echo 直 "$QUALITY" # short text

# color
if [ "$QUALITY" -ge 70 ]; then
  echo "#50fa7b"
else
  echo "#ff5555"
fi
